#!/usr/bin/env ruby

load './tasks.rb'

M = ActiveRecord::Migration
def up
  M.create_table :tasks do |t|
    t.string :title
    t.text :description
    t.boolean :done
    t.integer :pos
    t.timestamps
  end
end

def down
  M.drop_table :tasks
end

case $*[0]
when "up" then up
when "down" then down
when "reset" then down; up
end
