// Generated by CoffeeScript 1.6.3
(function() {
  window.gmapInit = function() {
    var map, mapOptions;
    mapOptions = {
      center: new google.maps.LatLng(49.61071, 30.121078),
      zoom: 4,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
    window.map = map;
    return addGrid();
  };

  window.addMarker = function(latlng, map) {
    map = map || window.map;
    return new google.maps.Marker({
      map: map,
      position: new google.maps.LatLng(latlng[0], latlng[1])
    });
  };

  window.setCenter = function(latlng, map) {
    map = map || window.map;
    return map.setCenter(new google.maps.LatLng(latlng[0], latlng[1]));
  };

  window.addGrid = function() {
    var coord, _i, _len, _ref, _results;
    _ref = window.grids;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      coord = _ref[_i];
      _results.push(addMarker(coord));
    }
    return _results;
  };

  google.maps.event.addDomListener(window, 'load', gmapInit);

}).call(this);
